spring:
  application:
    name: chat-server
  profiles:
    active: dev

  #阿里nacos配置中心地址.必须要在bootstrap.yml配置
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
---
#开发环境
spring:
  profiles: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml

---
#测试环境
spring:
  profiles: test
  cloud:
    nacos:
      config:
        server-addr: 192.168.1.133:8848
        file-extension: yaml

---
#生产环境
spring:
  profiles: prod
  cloud:
    nacos:
      config:
        server-addr: xxx:8848
        file-extension: yaml
